The problem is the V8 Statement object might end up not being referenced and destructed by GC before async execution ends.
statement.cpp line 25
Statement::~Statement() {
  delete m_baton;
  m_baton = NULL;
}

delete m_baton might be called before
EIO_AfterExecute  (line 87) is being called
req->data will be garaged

also fixed with double casting
../src/executeBaton.cpp:271:123: error: call to 'pow' is ambiguous